### ISSUE TITLE
No space provided for between the keyboard and the text view.

### ISSUE THREAD

**Issue by orospakr** [michaelhenry/KeyboardAvoider#4]
As you can see in the example GIFs, the revealed text view and the onscreen keyboard are right next to either other, with 0px of space between them. It would be more attractive with a little bit of extra spacing.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/16714/72841450-62c9a600-3c64-11ea-9c6c-25d479668eec.png">

**Comment by michaelhenry** [comment]
@orospakr yes, you’re right. I will look into it and update this repo. Thanks

**Comment by michaelhenry** [comment]
@orospakr it's now available in `v1.0.2`. please check when you have time. thank you

**Comment by orospakr** [comment]
Hey @michaelhenry, I decided to opt for a simpler approach for now, but thank you for the quick turn around time :)
